# Generated by Django 2.0 on 2018-02-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FT_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FT_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('vendor_can_see', models.BooleanField()),
                ('is_finalized', models.BooleanField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='MC_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MC_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MC_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('vendor_can_see', models.BooleanField()),
                ('is_finalized', models.BooleanField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='mc_choice',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.MC_Q'),
        ),
        migrations.AddField(
            model_name='mc_a',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.MC_Choice'),
        ),
        migrations.AddField(
            model_name='mc_a',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.MC_Q'),
        ),
        migrations.AddField(
            model_name='ft_a',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.FT_Q'),
        ),
        migrations.AddField(
            model_name='access',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Event'),
        ),
    ]
